# Generated by Django 3.2 on 2021-06-16 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nyumba', '0011_store_space_availability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unsuccesful_Room_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MerchantRequestID', models.CharField(max_length=50)),
                ('CheckoutRequestID', models.CharField(max_length=50)),
                ('ResultCode', models.IntegerField()),
                ('ResultDesc', models.TextField()),
                ('Paid_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyumba.room_application')),
                ('Paying_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'unsuccesful Room transaction',
                'verbose_name_plural': 'unsuccesful Room transactions',
            },
        ),
        migrations.CreateModel(
            name='Succesful_Room_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MerchantRequestID', models.CharField(max_length=50)),
                ('CheckoutRequestID', models.CharField(max_length=50)),
                ('ResultCode', models.IntegerField()),
                ('ResultDesc', models.TextField()),
                ('Amount', models.DecimalField(decimal_places=3, max_digits=13)),
                ('MpesaReceiptNumber', models.CharField(max_length=50)),
                ('Balance', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('TransactionDate', models.DateTimeField()),
                ('PhoneNumber', models.CharField(max_length=13)),
                ('Paid_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyumba.room_application')),
                ('Paying_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Succesful Room Payment',
                'verbose_name_plural': 'Succesful Room Payments',
            },
        ),
        migrations.CreateModel(
            name='Mpesa_api_Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MerchantRequestID', models.CharField(max_length=50)),
                ('CheckoutRequestID', models.CharField(max_length=50)),
                ('ResponseCode', models.IntegerField()),
                ('ResponseDescription', models.TextField()),
                ('CustomerMessage', models.TextField()),
                ('the_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mpesa Response',
                'verbose_name_plural': 'Mpesa Responses',
            },
        ),
    ]
