# Generated by Django 3.2 on 2021-07-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MpesaPayments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='succesful_room_payments',
            name='CheckoutRequestID',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='succesful_room_payments',
            name='MerchantRequestID',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='succesful_room_payments',
            name='MpesaReceiptNumber',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='succesful_room_payments',
            name='PhoneNumber',
            field=models.CharField(max_length=50),
        ),
    ]
